worker_processes  1;
daemon on;
master_process off;
error_log /private/tmp/claude-501/-Users-u5-ngx-rust/8749f61f-75a3-44d1-bce9-91757d2151c5/scratchpad/vts/t/servroot/logs/error.log debug;
pid       /private/tmp/claude-501/-Users-u5-ngx-rust/8749f61f-75a3-44d1-bce9-91757d2151c5/scratchpad/vts/t/servroot/logs/nginx.pid;
env MOCKEAGAIN_VERBOSE;
env MOCKEAGAIN;
env MOCKEAGAIN_WRITE_TIMEOUT_PATTERN;
env LD_PRELOAD;
env LD_LIBRARY_PATH;
env DYLD_INSERT_LIBRARIES;
env DYLD_FORCE_FLAT_NAMESPACE;
#env LUA_PATH;
#env LUA_CPATH;



http {
    access_log /private/tmp/claude-501/-Users-u5-ngx-rust/8749f61f-75a3-44d1-bce9-91757d2151c5/scratchpad/vts/t/servroot/logs/access.log;
    #access_log off;

    default_type text/plain;
    keepalive_timeout  68000ms;

    vts_zone main 1m;

    resolver 127.0.0.1:18661 valid=1s ipv6=off;
    resolver_timeout 2s;

    upstream backend {
        zone backend 1m;
        server 127.0.0.1:1 down;
        server vts-test.example:1984 resolve backup;
    }

    server {
        listen          1984;
        #placeholder
        server_name     'localhost';
        
        client_max_body_size 30M;
        #client_body_buffer_size 4k;

        # Begin preamble config...

        # End preamble config...

        # Begin test case config...
    location /ok     { return 200 "OK"; }
    location /up     {
        proxy_connect_timeout 1s;
        proxy_next_upstream off;
        proxy_pass http://backend/ok;
    }
    location /status { vts_status; }

        # End test case config.

        location / {
            root /private/tmp/claude-501/-Users-u5-ngx-rust/8749f61f-75a3-44d1-bce9-91757d2151c5/scratchpad/vts/t/servroot/html;
            index index.html index.htm;
        }
    }
}



#timer_resolution 100ms;

events {
    accept_mutex off;

    worker_connections  64;
}
env ASAN_OPTIONS;
env MOCKNOEAGAIN_VERBOSE;
env MOCKNOEAGAIN;
